server:
  port: 7000
spring:
  application:
    name: product-server
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql:///aigou?useUnicode=true&characterEncoding=UTF-8    
