server:
  port: 4000
spring:
  application:
    name: zuul

zuul:
  ignoredServices: '*'  # 忽略所有
  routes:
    plat:
      path: /plat/**  # 平台服务的请求路径
      serviceId: plat-server
    product:
      path: /product/**  # 商品服务的请求路径
      serviceId: product-server
  prefix: /service # 请求前缀




